[project]
name = "scl-outage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles==25.1.0",
    "cachetools==7.2.0",
    "filelock==4.0.3",
    "gunicorn==26.2.0",
    "httpx==0.28.1",
    "pillow==12.3.0",
    "matplotlib==3.10.8",
    "quart==0.23.1",
    "shapely==2.1.2",
    "pyogrio==0.13.0",
    "pyproj==3.8.0",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
]

[tool.uv]
default-groups = []
